// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDnogC47mMmzn7fHjG4MuohVtd2rxbYdM',
    appId: '1:569928956027:web:f02b85dfecdefb4b560ade',
    messagingSenderId: '569928956027',
    projectId: 'aiteacher-3a072',
    authDomain: 'aiteacher-3a072.firebaseapp.com',
    storageBucket: 'aiteacher-3a072.firebasestorage.app',
    measurementId: 'G-FBGY06BNRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5au7ORfrymkMqmc-5BiXnK6vQFEZTRuI',
    appId: '1:569928956027:android:6321f05d2511885c560ade',
    messagingSenderId: '569928956027',
    projectId: 'aiteacher-3a072',
    storageBucket: 'aiteacher-3a072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx0UeP8YrsHA4sU0Ee1AbaOuQFqqsDyhk',
    appId: '1:569928956027:ios:5e4e5fb7a5eb1965560ade',
    messagingSenderId: '569928956027',
    projectId: 'aiteacher-3a072',
    storageBucket: 'aiteacher-3a072.firebasestorage.app',
    iosBundleId: 'com.aakib.aiTeacher01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx0UeP8YrsHA4sU0Ee1AbaOuQFqqsDyhk',
    appId: '1:569928956027:ios:5e4e5fb7a5eb1965560ade',
    messagingSenderId: '569928956027',
    projectId: 'aiteacher-3a072',
    storageBucket: 'aiteacher-3a072.firebasestorage.app',
    iosBundleId: 'com.aakib.aiTeacher01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDnogC47mMmzn7fHjG4MuohVtd2rxbYdM',
    appId: '1:569928956027:web:1fa4dde8869690bd560ade',
    messagingSenderId: '569928956027',
    projectId: 'aiteacher-3a072',
    authDomain: 'aiteacher-3a072.firebaseapp.com',
    storageBucket: 'aiteacher-3a072.firebasestorage.app',
    measurementId: 'G-V4Y265JE5V',
  );

}